### ISSUE TITLE
multiprocessing crashing under windows

### ISSUE THREAD

**Issue by ekmungi** [MIC-DKFZ/trixi#1]
Seems like on windows some issue with spawning a thread on windows. There is a reference to this problem on pytorch documentation: 

https://pytorch.org/docs/stable/notes/windows.html#usage-multiprocessing

Any chance there is a quickfix for this?

c:\dev\libs\trixi\trixi\__init__.py:3: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'Qt5Agg' by the following code:
  File "giana_dataloader.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "C:\dev\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "C:\dev\anaconda3\lib\site-packages\matplotlib\backends\__init__.py", line 16, in <module>
    line for line in traceback.format_stack()

  if use_agg: matplotlib.use("Agg")
Traceback (most recent call last):
  File "giana_dataloader.py", line 218, in <module>
    train(image_gt_file_list_all)
  File "giana_dataloader.py", line 164, in train
    mylog = pvl(name='GIANA')
  File "c:\dev\libs\trixi\trixi\logger\visdom\pytorchvisdomlogger.py", line 23, in __init__
    super(PytorchVisdomLogger, self).__init__(*args, **kwargs)
  File "c:\dev\libs\trixi\trixi\logger\visdom\numpyvisdomlogger.py", line 64, in __init__
    self._process.start()
  File "C:\dev\anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\dev\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\dev\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\dev\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\dev\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Visdom.setup_socket.<locals>.run_socket'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\dev\libs\trixi\trixi\logger\visdom\numpyvisdomlogger.py", line 852, in exit
    self._process.terminate()
  File "C:\dev\anaconda3\lib\multiprocessing\process.py", line 116, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'

c:\dev\libs\trixi\trixi\__init__.py:3: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'Qt5Agg' by the following code:
  File "<string>", line 1, in <module>
  File "C:\dev\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\dev\anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\dev\anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\dev\anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\dev\anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\dev\anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\dev\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\dev\endovis2018-challenge\giana\dataloader\giana_dataloader.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "C:\dev\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "C:\dev\anaconda3\lib\site-packages\matplotlib\backends\__init__.py", line 16, in <module>
    line for line in traceback.format_stack()
  if use_agg: matplotlib.use("Agg")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\dev\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\dev\anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by elpequeno** [comment]
This is actually a problem of how python multiprocessing works on Windows. In our current implementation, we do therefore not support Windows, I am sorry. But we are working on both, a workaround and a more stable solution.
