### ISSUE TITLE
vlog in pytorch_experiment.py

### ISSUE THREAD

**Issue by fedorsc** [MIC-DKFZ/trixi#14]
Hi,

I encounter a problem when I try to run pytorch_experiment.py from the examples dir. self.vlog seems to be None. I use trixi 0.1.2.1 via pip installation with visdom 0.1.8.8. This problem is not present in trixi 0.1.1.6. Here is the error message:

```
  File "~/.local/lib/python3.6/site-packages/trixi/experiment/experiment.py", line 71, in run
    self.setup()

  File "<ipython-input-8-fec987966c35>", line 34, in setup
    self.vlog.plot_model_structure(self.model,

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-a33583383f44> in <module>()
----> 1 exp.run()

~/.local/lib/python3.6/site-packages/trixi/experiment/experiment.py in run(self, setup)
    101             self._time_end = time.strftime("%y-%m-%d_%H:%M:%S", time.localtime(time.time()))
    102 
--> 103             raise e
    104 
    105     def run_test(self, setup=True):

~/.local/lib/python3.6/site-packages/trixi/experiment/experiment.py in run(self, setup)
     69 
     70             if setup:
---> 71                 self.setup()
     72                 self._setup_internal()
     73             self.prepare()

<ipython-input-8-fec987966c35> in setup(self)
     32 
     33         self.save_checkpoint(name="checkpoint_start")
---> 34         self.vlog.plot_model_structure(self.model,
     35                                        [self.config.batch_size, 1, 28, 28],
     36                                        name='Model Structure')

AttributeError: 'NoneType' object has no attribute 'plot_model_structure'
```

Since I did not change anything I guess this is a bug. Please let me know if you need more information.

Otherwise this is really cool project, thank you!

Best regards

**Comment by jenspetersen** [comment]
We recently changed how loggers are passed to the PytorchExperiment. You could specify loggers={"vlog": "visdom"} and it should work. You can also check the [documentation](https://trixi.readthedocs.io/en/latest/_api/trixi.experiment.html#module-trixi.experiment.pytorchexperiment) for a bit more info on this. Let me know if that fixed it for you! (but redoing the examples is on our todo list anyway...)

**Comment by fedorsc** [comment]
Thank you very much for that quick reply! Yes, specifying the logger worked!

In case anybody stumbles upon the same problem: in order to plot the model structure I had to modify the input_size to `[[self.config.batch_size, 1, 28, 28]]` (instead of `[self.config.batch_size, 1, 28, 28]`).

**Comment by weicheng113** [comment]
There maybe some more update again. But it is better to have pytorch_experiment.py updated also.

use loggers={"visdom": "visdom"} instead of loggers={"vlog": "visdom"}, which is because of pytorchexperiment.vlog(self) implementation.

```python
 exp = MNIST_experiment(config=c, name='experiment', n_epochs=c.n_epochs,
                           seed=42, base_dir='./experiment_dir',
                           loggers={"visdom": "visdom"})
```

pytorch torchvision.utils.save_image method signature below, but pytorchplotfilelogger.save_image_grid_static


```python
# pytorchplotfilelogger.save_image_grid_static
pytorchplotfilelogger.save_image_grid_static(...):
  tv_save_image(tensor=tensor, filename=img_file, **image_args) # this does not match save_image signature below.

# torchvision.utils.save_image method signature below
def save_image(
    tensor: Union[torch.Tensor, List[torch.Tensor]],
    fp: Union[Text, pathlib.Path, BinaryIO],
    format: Optional[str] = None,
    **kwargs
) -> None:
```

result in the error below:
```python
Unhandled exception in thread started by <function PytorchPlotFileLogger.save_image_grid_static at 0x000002456711CAF8>
Traceback (most recent call last):
  File "C:\Users\...\lib\site-packages\trixi\logger\file\pytorchplotfilelogger.py", line 183, in save_image_grid_static
    tv_save_image(tensor=tensor, filename=img_file, **image_args)
  File "C:\Users\...t\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
TypeError: save_image() missing 1 required positional argument: 'fp'
```
